name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - matplotlib-base=3.7.0
  - pyproj=3.3.1
  - folium=0.13.0
  - streamlit=1.19.0
  - streamlit-folium=0.11.1
  - geopandas=0.12.2
  
