name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.12.2=pyhd8ed1ab_0
  - pandas=1.5.3=py310h1c4a608_0
  - matplotlib-base=3.7.0=py310h51140c5_0
  - pyproj=3.3.1=py310h1bcc3f4_0
  - streamlit=1.19.0=pyhd8ed1ab_0
  - streamlit-folium=0.11.1=pyhd8ed1ab_0
  - folium=0.13.0=pyhd8ed1ab_0
  